---
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(deps)'
    cooldown:
      default-days: 7
    groups:
      xterm:
        patterns:
          - '@xterm/*'
      fontawesome:
        patterns:
          - '@fortawesome/*'
      socket-io:
        patterns:
          - 'socket.io'
          - 'socket.io-client'
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      esbuild:
        patterns:
          - 'esbuild*'
      typescript:
        patterns:
          - 'typescript*'
          - '@typescript-eslint/*'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'ci(deps)'
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - 'actions/*'
      docker:
        patterns:
          - 'docker/*'
      codeql:
        patterns:
          - 'github/codeql-action/*'
  - package-ecosystem: docker
    directory: '/containers'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(deps)'
    cooldown:
      default-days: 7
