[[repos]]
repo = "local"

  [[repos.hooks]]
  id = "eslint"
  name = "ESLint"
  language = "system"
  entry = "pnpm exec eslint --fix"
  files = '\.(js|ts)$'

  [[repos.hooks]]
  id = "prettier"
  name = "Prettier"
  language = "system"
  entry = "pnpm exec prettier --write"
  files = '\.(json|scss|md)$'

  [[repos.hooks]]
  id = "commitlint"
  name = "Commitlint"
  language = "system"
  entry = "pnpm exec commitlint --edit"
  stages = ["commit-msg"]
  pass_filenames = false
