export const validThemes = new Set([
  'default',
  'dark',
  'light',
  'dracula',
  'solarized-dark',
  'solarized-light',
  'gruvbox-dark',
  'nord',
  'catppuccin-mocha',
  'catppuccin-macchiato',
  'catppuccin-frappe',
  'catppuccin-latte',
  'monokai',
  'tokyo-night',
  'tokyo-night-storm',
  'tokyo-night-moon',
  'one-dark',
  'cobalt2',
  'snazzy',
  'c64',
  'ibm-cga',
  'apple-classic',
  'matrix',
  'zenburn',
]);

export const themeBackgrounds: Record<string, string> = {
  default: '#000000',
  dark: '#000000',
  light: '#ffffff',
  dracula: '#282a36',
  'solarized-dark': '#002b36',
  'solarized-light': '#fdf6e3',
  'gruvbox-dark': '#282828',
  nord: '#2e3440',
  'catppuccin-mocha': '#1e1e2e',
  'catppuccin-macchiato': '#24273a',
  'catppuccin-frappe': '#303446',
  'catppuccin-latte': '#eff1f5',
  monokai: '#272822',
  'tokyo-night': '#1a1b26',
  'tokyo-night-storm': '#24283b',
  'tokyo-night-moon': '#222436',
  'one-dark': '#282c34',
  cobalt2: '#132738',
  snazzy: '#1e1f29',
  c64: '#40318d',
  'ibm-cga': '#141414',
  'apple-classic': '#2c2b2b',
  matrix: '#0f191c',
  zenburn: '#3f3f3f',
};

export function isValidTheme(name: string): boolean {
  return validThemes.has(name);
}
