---
name: Build & Test
on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
permissions:
  contents: read
jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 2
          persist-credentials: false

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup env
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: ESLint checks
        run: pnpm lint

      - run: pnpm build
        name: Compile Typescript

      - run: pnpm test
        name: Run tests
        env:
          CI: true

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
