---
name: Publish
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Publish to GitHub Packages
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Docker Publish Image
    uses: ./.github/workflows/docker.workflow.yml
    secrets: inherit
    with:
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      push: true
