---
name: Pull Request
on:
  pull_request:
permissions: {}
jobs:
  commitlint:
    name: Lint Commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Validate PR commits
        run: pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.workflow.yml

  validate-docker:
    name: Validate Docker Build
    uses: ./.github/workflows/docker.workflow.yml
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    with:
      platforms: ${{ matrix.platform }}
      push: false
