---
name: Pull Request
on:
  pull_request:
jobs:
  commitlint:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Validate PR commits
        run: pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.workflow.yml

  validate-docker:
    name: Validate Docker Build
    uses: ./.github/workflows/docker.workflow.yml
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    secrets: inherit
    with:
      platforms: ${{ matrix.platform }}
      push: false
